version: '3.9'

services:
  apimysql:
    image: apimysql:1.0
    build:
      context: .
    ports:
      - 8080:5000
    networks:
      - apimysql-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ApiMysql
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: maravilha
    volumes:
      - db-data:/var/lib/mysql
      - ./Scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - apimysql-network

networks:
  apimysql-network:
    driver: bridge

volumes:
    db-data: